/** Language-neutral site metadata: links, images, identity. */
export const siteConfig = {
  name: 'Kayblis',
  email: 'shallowaria@gmail.com',
  website: 'www.kayblis.dev',
  resumeUrl: '/resume.pdf',

  // Decorative forest backdrop (also used as the hero image).
  heroImage: '/hero-bg-1078.webp',

  social: {
    github: 'https://github.com/shallowaria',
    twitter: 'https://x.com/Kaybliscy',
    bilibili: 'https://space.bilibili.com/7213886',
  },

  // Contact handles shown in the Contact section (replace the placeholders).
  contact: {
    qq: '123456789',
    wechat: 'kayblis',
    phone: '+86 138 0000 0000',
  },

  /**
   * Responsive image sources. Each `srcSet` lists width-resized WebP variants
   * (generated by `pnpm optimize:images` from /image-sources into /public) so
   * the browser downloads only the resolution a device needs. `sizes` tells it
   * the rendered width; `src` is the largest variant as a fallback.
   */
  images: {
    hero: {
      src: '/hero-bg-1078.webp',
      srcSet:
        '/hero-bg-480.webp 480w, /hero-bg-768.webp 768w, /hero-bg-1078.webp 1078w',
      sizes: '100vw',
      width: 1078,
      height: 1459,
    },
    about: {
      src: '/about-portrait-768.webp',
      srcSet:
        '/about-portrait-384.webp 384w, /about-portrait-640.webp 640w, /about-portrait-768.webp 768w',
      sizes: '(min-width: 1024px) 340px, 100vw',
      width: 1402,
      height: 1122,
    },
    quote: {
      src: '/quote-foliage-384.webp',
      srcSet: '/quote-foliage-192.webp 192w, /quote-foliage-384.webp 384w',
      sizes: '(min-width: 640px) 192px, 160px',
    },
    // The little wanderer that loops the contact border (rendered at 48px).
    scrollbarThumb: {
      src: '/scrollbar-thumb-96.webp',
      srcSet: '/scrollbar-thumb-96.webp 96w, /scrollbar-thumb-192.webp 192w',
    },
    // Project covers keep their src in the i18n content (per-language captions),
    // these provide width-aware loading hints by index.
    projectSizes: '(min-width: 640px) 176px, 100vw',
  },
}
